alias manage='poetry run ./manage.py'
alias makemigrations='poetry run ./manage.py makemigrations'
alias migrate='poetry run ./manage.py migrate'
alias shell='poetry run ./manage.py shell_plus'
alias testkeep='poetry run ./manage.py test --keepdb'