databases:
  - name: candfans-analyzer-db
    region: singapore
    plan: free
    databaseName: candfansanalyzer
    user: appuser
    ipAllowList: []

services:
  - type: web
    name: candfans-analyzer
    region: singapore
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: ./docker/nginx/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: pserv
          name: candfans-analyzer-backend
          property: host
      - key: BACKEND_PORT
        fromService:
          type: pserv
          name: candfans-analyzer-backend
          property: port

  - type: pserv
    name: candfans-analyzer-backend
    region: singapore
    plan: starter
    runtime: docker
    dockerContext: .
    dockerfilePath: ./docker/app/Dockerfile
    dockerCommand: /app/docker/app/run.sh
    envVars:
      - fromGroup: django-shared
      - key: SERVICE_DOMAIN
        fromService:
          type: web
          name: candfans-analyzer
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: candfans-analyzer-db
          property: connectionString
      - key: REDIS_HOSTNAME
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: port

  - type: worker
    name: candfans-analyzer-rq
    region: singapore
    plan: starter
    runtime: docker
    dockerContext: .
    dockerfilePath: ./docker/app/Dockerfile
    dockerCommand: /app/docker/app/run_worker.sh
    envVars:
      - fromGroup: django-shared
      - key: SERVICE_DOMAIN
        fromService:
          type: web
          name: candfans-analyzer
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: candfans-analyzer-db
          property: connectionString
      - key: REDIS_HOSTNAME
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: port

  - type: cron
    name: candfans-analyzer-resync-users-job
    region: singapore
    plan: starter
    runtime: docker
    dockerContext: .
    dockerfilePath: ./docker/app/Dockerfile
    dockerCommand: poetry run python ./manage.py resync_users
    schedule: 13 */8 * * *
    envVars:
      - fromGroup: django-shared
      - key: SERVICE_DOMAIN
        fromService:
          type: web
          name: candfans-analyzer
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: candfans-analyzer-db
          property: connectionString
      - key: REDIS_HOSTNAME
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: candfans-analyzer-redis
          property: port

  - type: redis
    name: candfans-analyzer-redis
    plan: free # Default: starter
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru


envVarGroups:
  - name: django-shared
    envVars:
      - key: DJANGO_ENV
        value: 'production'
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_DB
        value: 0
      - key: SYNC_EXPIRED_DAYS
        value: 1
