# Generated by Django 4.2.10 on 2024-03-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_candfansuser_created_at_candfansuser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandfansUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_code', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('profile_cover_img', models.CharField(max_length=255)),
                ('profile_text', models.CharField(max_length=255)),
                ('profile_img', models.CharField(max_length=255)),
                ('creater_genre', models.IntegerField()),
                ('link_twitter', models.CharField(max_length=255)),
                ('link_instagram', models.CharField(max_length=255)),
                ('link_tiktok', models.CharField(max_length=255)),
                ('link_youtube', models.CharField(max_length=255)),
                ('link_amazon', models.CharField(max_length=255)),
                ('link_facebook', models.CharField(max_length=255)),
                ('link_website', models.CharField(max_length=255)),
                ('apeal_img1', models.CharField(max_length=255)),
                ('apeal_img2', models.CharField(max_length=255)),
                ('apeal_img3', models.CharField(max_length=255)),
                ('follower_cnt', models.IntegerField(default=0)),
                ('follow_cnt', models.IntegerField(default=0)),
                ('like_cnt', models.IntegerField(default=0)),
                ('fans_cnt', models.IntegerField(null=True)),
                ('post_cnt', models.IntegerField(default=0)),
                ('image_cnt', models.IntegerField(default=0)),
                ('movie_cnt', models.IntegerField(default=0)),
                ('is_follow', models.BooleanField(default=False)),
                ('is_followed', models.BooleanField(default=False)),
                ('is_fansed', models.BooleanField(default=False)),
                ('is_block', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_ban', models.BooleanField(default=False)),
                ('can_send_dm', models.BooleanField(default=False)),
                ('delete_at', models.CharField(max_length=255, null=True)),
                ('is_accept_comment', models.BooleanField(default=False)),
                ('is_official_creator', models.BooleanField(default=False)),
                ('live_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='candfansuser',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.candfansuserdetail'),
        ),
    ]
