# Generated by Django 4.2.10 on 2024-03-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_candfansuserdetail_candfansuser_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candfansuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
