# Generated by Django 4.2.10 on 2024-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_rename_user_name_candfansuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='candfansuserdetail',
            name='is_on_air',
            field=models.BooleanField(default=False),
        ),
    ]
