# Generated by Django 4.2.10 on 2024-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_candfansuserdetail_is_on_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='candfansuser',
            name='sync_status',
            field=models.CharField(choices=[('SYNCING', 'SYNCING'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], max_length=100, null=True),
        ),
    ]
