# Generated by Django 4.2.10 on 2024-03-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_candfansuser_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candfansuser',
            name='sync_requested_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
