# Generated by Django 4.2.10 on 2024-03-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_candfansuser_sync_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandfansPlan',
            fields=[
                ('plan_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('support_price', models.IntegerField()),
                ('total_support_price', models.IntegerField()),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_detail', models.TextField()),
                ('backnumber_id', models.IntegerField(null=True)),
                ('backnumber_price', models.IntegerField(null=True)),
                ('total_backnumber_price', models.IntegerField(null=True)),
                ('can_see_backnumber_plan_pay', models.BooleanField()),
                ('can_buy_backnumber_not_entry_plan', models.BooleanField()),
                ('add_backnumber_date', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.candfansuser')),
            ],
        ),
        migrations.CreateModel(
            name='CandfansPost',
            fields=[
                ('post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=50)),
                ('user_code', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('profile_img', models.CharField(max_length=500)),
                ('profile_cover_img', models.CharField(max_length=500)),
                ('post_date', models.CharField(max_length=50)),
                ('contents_type', models.IntegerField()),
                ('post_type', models.IntegerField()),
                ('contents_text', models.TextField()),
                ('over_contents_50str', models.IntegerField()),
                ('price', models.IntegerField()),
                ('limit_post_date', models.CharField(max_length=50)),
                ('reserve_post_date', models.CharField(max_length=50)),
                ('contents_path1', models.CharField(max_length=500, null=True)),
                ('contents_path2', models.CharField(max_length=500, null=True)),
                ('contents_path3', models.CharField(max_length=500, null=True)),
                ('contents_path4', models.CharField(max_length=500, null=True)),
                ('image_count', models.IntegerField()),
                ('movie_time', models.FloatField(null=True)),
                ('secret_file', models.CharField(max_length=500, null=True)),
                ('thumbnail_file', models.CharField(max_length=500)),
                ('like_cnt', models.IntegerField()),
                ('comments_cnt', models.IntegerField()),
                ('chip_cnt', models.IntegerField()),
                ('is_like', models.BooleanField()),
                ('can_browsing', models.BooleanField()),
                ('can_send_chip', models.BooleanField()),
                ('r18', models.IntegerField()),
                ('apply_status', models.IntegerField()),
                ('is_progressed', models.BooleanField()),
                ('is_accept_comment', models.BooleanField()),
                ('can_read_text', models.BooleanField()),
                ('is_official_creator', models.BooleanField()),
                ('has_own_thumbnail', models.BooleanField()),
                ('is_on_air', models.BooleanField()),
                ('live_url', models.CharField(blank=True, max_length=500, null=True)),
                ('plans', models.ManyToManyField(related_name='posts', to='analyzer.candfansplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.candfansuser')),
            ],
        ),
    ]
