# Generated by Django 4.2.10 on 2024-03-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_candfansplanfanshistory_original_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candfanspost',
            name='plans',
        ),
        migrations.CreateModel(
            name='CandFansPostPlanRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candfans_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.candfansplan')),
                ('candfans_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.candfanspost')),
            ],
        ),
    ]
