# Generated by Django 4.2.10 on 2024-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_remove_candfanspost_plans_candfanspostplanrelation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candfanspostplanrelation',
            constraint=models.UniqueConstraint(fields=('candfans_plan', 'candfans_post'), name='candfans_post_plan_rel_uniq'),
        ),
    ]
