# Generated by Django 4.2.10 on 2024-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_candfanspostplanrelation_candfans_post_plan_rel_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candfansuserdetail',
            name='profile_img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candfansuserdetail',
            name='profile_text',
            field=models.TextField(),
        ),
    ]
