# Generated by Django 4.2.10 on 2024-03-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_alter_candfansuserdetail_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candfanspostplanrelation',
            name='candfans_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candfans_plan_rel', to='analyzer.candfansplan'),
        ),
        migrations.AlterField(
            model_name='candfanspostplanrelation',
            name='candfans_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candfans_post_rel', to='analyzer.candfanspost'),
        ),
    ]
