# Generated by Django 4.2.10 on 2024-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='candfanspostplanrelation',
            name='backnumber_id',
            field=models.IntegerField(null=True),
        ),
    ]
