# Generated by Django 4.2.10 on 2024-07-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_candfanscreatordailyranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandfansCreatorDailyRanking',
        ),
    ]
