# Generated by Django 4.2.10 on 2024-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_delete_candfanscreatordailyranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandfansCreatorDailyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rank', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_code', models.CharField(max_length=255)),
                ('username', models.TextField()),
                ('profile_img', models.CharField(max_length=500)),
                ('profile_text', models.TextField()),
                ('follow_cnt', models.IntegerField()),
                ('follower_cnt', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('is_official_creator', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('day', 'user_id')},
            },
        ),
    ]
