# Generated by Django 4.2.10 on 2024-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_candfanscreatordailyranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='candfansuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
