# Generated by Django 4.2.10 on 2024-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0019_candfansuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandfansRankingCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rank', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_code', models.CharField(max_length=255)),
                ('username', models.TextField()),
                ('follow_cnt', models.IntegerField()),
                ('follower_cnt', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('is_official_creator', models.BooleanField()),
                ('plans', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('day', 'user_id')},
            },
        ),
    ]
