# Generated by Django 4.2.10 on 2024-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0020_candfansrankingcreator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandfansCreatorDailyRanking',
            new_name='OldCandfansCreatorDailyRanking',
        ),
    ]
