# Generated by Django 4.2.10 on 2024-09-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0021_rename_candfanscreatordailyranking_oldcandfanscreatordailyranking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandfansRankingCreator',
            new_name='CandfansCreatorDailyRanking',
        ),
    ]
